package com.isu.common.utils

object ManageFeatures {
    const val PAY: String = "Pay"
    const val OFFERS: String = "Offers"
    const val LINK_CARD: String = "Link\nCard"
    const val REQUEST_CARD: String = "Request Card"
    const val RE_ISSUANCE: String = "Card\nReissuance"
    const val CARD_STATUS = "Card\nStatus"
    const val MODIFY_PIN = "Modify\nPIN"
    const val MANAGE_NFC = "Manage\nNFC"
    const val MCC = "Merchant\nCategory Code"
    const val ORDER_HISTORY: String = "Order\nHistory"
    const val LOAD_CARD: String = "Load\nCard"
    const val MANDATES:String = "Mandates"
    const val TRANSACTION_SETTINGS: String = "Transaction Settings"
    const val TOKENS: String = "Tokens"
    const val SPEND_ANALYTICS: String = "Spend Analytics"
    const val BENEFICIARY: String = "Beneficiary"
    const val MINI_STATEMENT : String = "Mini Statement"
    const val DETAILED_STATEMENT : String = "Detailed Statement"
    const val KIT_TO_KIT: String = "Kit to Kit Transfer"
    const val ORDER_PHYSICAL: String = "Order Physical Card"
    const val ADD_ON_CARD: String = "Add On Card"
    const val ACTIVE: String = "Activate"
    const val INACTIVE: String = "Inactive"
    const val DE_ACTIVATE: String = "Deactivate"
    const val TEMP_BLOCK: String = "Temp Block"
    const val LOST: String = "Lost"
    const val STOLEN = "Stolen"
    const val DAMAGE: String = "Damage"
}
